export const theme = {
  colors: {
    primary: '#a9978b',
    primaryLight: '#c4b8ad',
    primaryDark: '#8b7d70',
    primarySoft: '#a9978b15',
    primaryGhost: '#a9978b08',
    white: '#ffffff',
    background: '#ffffff',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    text: {
      primary: '#2d2926',
      secondary: '#5a524e',
      tertiary: '#8b7d70',
      muted: '#a9978b',
      light: '#c4b8ad',
      inverse: '#ffffff',
    },
    border: {
      light: '#f5f3f1',
      default: '#e8e3df',
      primary: '#a9978b',
      subtle: '#f9f7f5',
    },
    accent: '#a9978b',
    error: '#c44536',
    success: '#6b8e23',
    warning: '#d4851a',
    info: '#5a524e',
  },
  spacing: {
    xs: 6,
    sm: 12,
    md: 20,
    lg: 28,
    xl: 40,
    xxl: 60,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  typography: {
    sizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 24,
      xxl: 30,
    },
    weights: {
      light: '300' as const,
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
    },
  },
  shadows: {
    soft: {
      shadowColor: '#a9978b',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    light: {
      shadowColor: '#a9978b',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 3,
    },
    medium: {
      shadowColor: '#a9978b',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 20,
      elevation: 5,
    },
    elegant: {
      shadowColor: '#2d2926',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 4,
      elevation: 1,
    },
  },
};

export type Theme = typeof theme;